pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Artifact is ready and reploying on QA env') {
            steps {
                   build job : 'Tomcat-application-deploy-to-QA-env'
            }   
        }            
      
    }
}
